### ISSUE TITLE
Feature request: Feed monitoring time window/cron in docker

### ISSUE THREAD

**Issue by hazzuk** [VerifiedJoseph/vigilant#189]
### Summary
Add a new parameter for feeds which allows specifying the window of time during the day in which a feed is actively monitored.

### Examples
```
cron: 0 9-22 * * *        (would probably have to override 'interval')

or

start_time: 9am
end_time: 10pm

or

active_hours: 9am-10pm

or

time_window: 9am-10pm
```

### Motivation
Everything I currently monitor is based on people doing something. So being able to set a window of time, and pause monitoring a feed at night would be useful. It can prevent sending loud notifications during the evening, but keeping the ntfy priority high for use during the day. Also reduces the likelihood of being rate limited with feeds, as I could cut the number of requests per day in half.

**Comment by VerifiedJoseph** [comment]
This feature is available in [v1.4.0](https://github.com/VerifiedJoseph/vigilant/releases/tag/v1.4.0) as [active hours](https://github.com/VerifiedJoseph/vigilant/blob/main/docs/feeds.md#active-hours).

Example:
```YAML
feeds:
    - name: GitHub Status
      url: https://www.githubstatus.com/history.rss
      interval: 600
      active_hours:
        start_time: '09:30'
        end_time: '17:00'
````
