### ISSUE TITLE
Icon in title

### ISSUE THREAD

**Issue by er2de2** [VerifiedJoseph/vigilant#317]
Hello, i like your app very much.
Is it possible to add a custom icon to the title_prefix?

**Comment by VerifiedJoseph** [comment]
You can use [emojis](https://www.everyemoji.com/) to add an icon to a feed's title_prefix.

Example: 
```YAML
feeds:
    - name: GitHub status
      url: https://www.githubstatus.com/history.rss
      interval: 600
      title_prefix: "⚠"
```
