### ISSUE TITLE
NWS CAP ATOM feeds causing crash

### ISSUE THREAD

**Issue by PhilRW** [VerifiedJoseph/vigilant#403]
### Describe the bug

```
PHP Fatal error:  Uncaught TypeError: html_entity_decode(): Argument #1 ($string) must be of type string, null given in /app/src/Check.php:145
Stack trace:
#0 /app/src/Check.php(145): html_entity_decode()
#1 /app/src/Check.php(97): Vigilant\Check->process()
#2 /app/vigilant.php(32): Vigilant\Check->check()
#3 {main}
 thrown in /app/src/Check.php on line 145
```

### Configuration

feeds.yaml:
```
feeds:
    - name: CO NWS alerts
      url: "https://api.weather.gov/alerts/active.atom?area=CO"
      interval: 300
```

### Version

1.5.1

###  Deployment Method

Docker compose
